[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

# API routes
[[redirects]]
  from = "/api/shorten"
  to = "/.netlify/functions/shorten"
  status = 200

# Short URL redirects - catch before SPA fallback
[[redirects]]
  from = "/:shortCode"
  to = "/.netlify/functions/redirect"
  status = 200

# Fallback to index for everything else
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200